In [1]:
import numpy as np # built on c++ as it requires faster computations therefore is faster

In [2]:
# numpy is faster because it uses arrays
np.__version__

'1.24.2'

In [3]:
print(np.__doc__)


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularly 

In [4]:
l = [1,2,3,4,5]   # supports heterogenous data


In [5]:
arr = np.array(l)   # array is the way numpy stores the data but stores only same type of data
              # how is it different from the list

In [6]:
type(np.array(l))

numpy.ndarray

In [7]:
arr.ndim

1

In [8]:
l = [1,2,3,4,5,"haris"]
arr1 = np.array(l)       # here the data type changes to string shown by U11
arr1

array(['1', '2', '3', '4', '5', 'haris'], dtype='<U11')

In [9]:
arr1 = np.array([[1,3,4],[6,7,8]])
arr1

array([[1, 3, 4],
       [6, 7, 8]])

In [10]:
arr1.ndim

2

In [11]:
l = [1,2,3,4]

In [12]:
mat = np.matrix(l)

In [13]:
# the no of square braces determine the dimension of the np array
l = [1,2,3,4,5,"haris"]

In [14]:
np.array(l)            # is one dimensional , can have  multiple dimensions

array(['1', '2', '3', '4', '5', 'haris'], dtype='<U11')

In [15]:
np.matrix(l)   # is two dimensional by default

matrix([['1', '2', '3', '4', '5', 'haris']], dtype='<U11')

In [16]:
np.matrix([[1,3],[5,7],[8,0]])

matrix([[1, 3],
        [5, 7],
        [8, 0]])

In [17]:
np.matrix([[[1,3],[5,7],[8,0]]])

ValueError: matrix must be 2-dimensional

In [18]:
np.array([[[1,3],[5,7],[8,0]]])

array([[[1, 3],
        [5, 7],
        [8, 0]]])

In [19]:
# mor way to convert to array
np.asarray([[1,3],[5,7],[8,0]])

array([[1, 3],
       [5, 7],
       [8, 0]])

In [20]:
# convert the input to an ndarray, but pass ndarray subclass through
np.asanyarray([[[1,3],[5,7],[8,0]]])

array([[[1, 3],
        [5, 7],
        [8, 0]]])

In [21]:
np.asanyarray(mat)   # it will not be converted to an array as it is the sub class of array and will simply pass through

matrix([[1, 2, 3, 4]])

In [22]:
np.asarray(mat)

array([[1, 2, 3, 4]])

In [23]:
np.array(mat)

array([[1, 2, 3, 4]])

In [24]:
t = ([1,3,4],[6,8,0])

In [25]:
type(t)

tuple

In [26]:
np.array(t)

array([[1, 3, 4],
       [6, 8, 0]])

In [27]:
a =5
np.array(a)

array(5)

In [28]:
l = [1,3,4,5,9]
arr = np.array(l)

In [29]:
arr[3]

5

In [30]:
# shallow copy "a" and "arr" point to same memory location
a = arr

In [31]:
arr[0] = 1000

In [32]:
arr

array([1000,    3,    4,    5,    9])

In [33]:
a

array([1000,    3,    4,    5,    9])

In [34]:
# deep copy creates a new reference so "b" and "a" refer to different memory location
b = a.copy()
b[0] = 2000

In [35]:
b

array([2000,    3,    4,    5,    9])

In [36]:
a

array([1000,    3,    4,    5,    9])

In [37]:
# ways to generate arrays
np.fromfunction(lambda i,j : i==j, shape = (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [38]:
np.fromfunction(lambda i,j : i==j, (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [39]:
arr1 = np.array([[1,2,3,4],[4,5,6,7]])
arr1

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [40]:
arr1.shape

(2, 4)

In [41]:
np.fromfunction(lambda i,j : i==j, shape = (3,1))

array([[ True],
       [False],
       [False]])

In [42]:
arr1.size

8

In [43]:
np.fromfunction(lambda i,j : i*j, (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [44]:
list(i for i in range(5))

[0, 1, 2, 3, 4]

In [45]:
list(range(5))

[0, 1, 2, 3, 4]

In [46]:
(i*i for i in range(5))   # generator

<generator object <genexpr> at 0x00000195FE2921F0>

In [47]:
# making iterable
iterable = (i*i for i in range(5))

In [48]:
np.fromiter(iterable, float)

array([ 0.,  1.,  4.,  9., 16.])

In [49]:
np.fromstring('23 34 67',sep = ' ')

array([23., 34., 67.])

In [50]:
np.fromstring('23,34,67',sep = ',')

array([23., 34., 67.])

In [51]:
np.fromstring('haris,nazir,lone',sep = ',')  # numbers in the string format can be converted otherwise not

C:\Users\haris nazir\AppData\Local\Temp\ipykernel_12048\1165604080.py:1: DeprecationWarning: string or file could not be read to its end due to unmatched data; this will raise a ValueError in the future.
  np.fromstring('haris,nazir,lone',sep = ',')  # numbers in the string format can be converted otherwise not


array([], dtype=float64)

In [52]:
arr1.dtype

dtype('int32')

In [53]:
l = [1,2,3,4]
arr = np.array(l)
arr.dtype

dtype('int32')

In [54]:
l = [1,2,3,4,'haris']
arr = np.array(l)
arr.dtype

dtype('<U11')

In [55]:
list(range(5))

[0, 1, 2, 3, 4]

In [56]:
range(5)

range(0, 5)

In [57]:
list(range(1.0,2.10))  # range cannot deal with float values in order to get float values we have np.arrange

TypeError: 'float' object cannot be interpreted as an integer

In [58]:
np.arange(0.1,10.2,0.3)     # important function in numpy

array([ 0.1,  0.4,  0.7,  1. ,  1.3,  1.6,  1.9,  2.2,  2.5,  2.8,  3.1,
        3.4,  3.7,  4. ,  4.3,  4.6,  4.9,  5.2,  5.5,  5.8,  6.1,  6.4,
        6.7,  7. ,  7.3,  7.6,  7.9,  8.2,  8.5,  8.8,  9.1,  9.4,  9.7,
       10. ])

In [59]:
np.linspace(1,5,20)    # 20 equally spaced values

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [60]:
np.logspace(1,5,20,base = 2)   # gives log of the values with base 2

array([ 2.        ,  2.31422047,  2.6778082 ,  3.09851928,  3.58532838,
        4.14862018,  4.80041088,  5.55460457,  6.42728981,  7.43708284,
        8.60552469,  9.95754072, 11.5219723 , 13.3321921 , 15.42681597,
       17.85052668, 20.65502717, 23.90014339, 27.65510059, 32.        ])

In [61]:
arr1 = np.zeros(5)
arr1

array([0., 0., 0., 0., 0.])

In [62]:
arr1.shape

(5,)

In [63]:
arr2 = np.zeros((3,4))
arr2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [64]:
arr2.shape

(3, 4)

In [65]:
arr3 = np.zeros((3,3,4))
arr3

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [66]:
arr3.shape    # repeat '3,4' three times 

(3, 3, 4)

In [67]:
arr3.ndim

3

In [68]:
arr4 = np.ones((2,3,4,5))
arr4

array([[[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]],


       [[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]]])

In [69]:
arr4.ndim

4

In [70]:
arr4+6

array([[[[7., 7., 7., 7., 7.],
         [7., 7., 7., 7., 7.],
         [7., 7., 7., 7., 7.],
         [7., 7., 7., 7., 7.]],

        [[7., 7., 7., 7., 7.],
         [7., 7., 7., 7., 7.],
         [7., 7., 7., 7., 7.],
         [7., 7., 7., 7., 7.]],

        [[7., 7., 7., 7., 7.],
         [7., 7., 7., 7., 7.],
         [7., 7., 7., 7., 7.],
         [7., 7., 7., 7., 7.]]],


       [[[7., 7., 7., 7., 7.],
         [7., 7., 7., 7., 7.],
         [7., 7., 7., 7., 7.],
         [7., 7., 7., 7., 7.]],

        [[7., 7., 7., 7., 7.],
         [7., 7., 7., 7., 7.],
         [7., 7., 7., 7., 7.],
         [7., 7., 7., 7., 7.]],

        [[7., 7., 7., 7., 7.],
         [7., 7., 7., 7., 7.],
         [7., 7., 7., 7., 7.],
         [7., 7., 7., 7., 7.]]]])

In [71]:
arr4*2

array([[[[2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2.]],

        [[2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2.]],

        [[2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2.]]],


       [[[2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2.]],

        [[2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2.]],

        [[2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2.]]]])

In [72]:
'''what is numpy?
   array
   list vs array
   why array is faster than list?
      1.homogenous
      2.memory allocation'''
# for lists data is stored at random locations list stores the adress of those elements which may or may not be contigeous
# thus list enables concepts of references and resizing(creates new bigger space to accumudate adresses in case of append ot list)
# array has statically defined contigeous  memory not dynamic as it has homogenous and fixed size
# 1d array --> vector
# 2d array --> matrix
# 3d array --> tensor

# vectorization operation: operation column wise


'what is numpy?\n   array\n   list vs array\n   why array is faster than list?\n      1.homogenous\n      2.memory allocation'

In [73]:
arr = np.ones((3,4))

In [74]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [75]:
arr+5

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [76]:
arr*5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [77]:
np.empty((3,4),int) # initializes random values to the matrix

array([[         0,          0,          0, 1072693248],
       [         0, 1073741824,          0,          0],
       [         0,          0,          0,          0]])

In [78]:
np.eye(5)     # always yields a diagonal square matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [79]:
np.eye(3,dtype = int)    # returns an identity matrix

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [80]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [81]:
import pandas as pd
pd.DataFrame(arr)

0    1    2    3
0  1.0  1.0  1.0  1.0
1  1.0  1.0  1.0  1.0
2  1.0  1.0  1.0  1.0

In [82]:
import random

In [83]:
random.choice((1,3,4,5,6,9))

3

In [84]:
random.choice('haris')

'a'

In [85]:
random.randrange(1,1000)

420

In [86]:
random.randrange(1,1000)

399

In [87]:
random.random()    # a random no is generated between 0 and 1 excluding 1

0.7025716522546084

In [88]:
lis = [1,3,5,7,9]
random.shuffle(lis)

In [89]:
lis

[7, 1, 3, 5, 9]

In [90]:
random.uniform(7,9)          # a no. between 7 and 9

7.7303444203381755

In [91]:
# above can be done using numpy using
np.random.rand(2,3)

array([[0.46873495, 0.82824679, 0.73391497],
       [0.16510862, 0.19682698, 0.17559003]])

In [92]:
np.random.rand(1)

array([0.44651448])

In [93]:
np.random.randn()

0.287932318887997

In [94]:
np.random.randn(2,3)

array([[-0.83816771,  0.39065841,  2.48953725],
       [-0.21966172, -0.95426377,  0.945792  ]])

In [95]:
np.random.random_sample()

0.685743552030472

In [96]:
np.random.randint(1,5,size = (2,3))

array([[2, 3, 2],
       [3, 2, 2]])

In [97]:
arr = np.random.randint(1,5,size = (3,4))
arr

array([[1, 4, 4, 1],
       [3, 2, 3, 4],
       [3, 2, 4, 4]])

In [98]:
arr.size

12

In [99]:
arr.shape

(3, 4)

In [100]:
arr.ndim

2

In [101]:
arr.reshape(2,6)            # array size should not change,multiples of array size

array([[1, 4, 4, 1, 3, 2],
       [3, 4, 3, 2, 4, 4]])

In [102]:
arr.reshape(12,1) 

array([[1],
       [4],
       [4],
       [1],
       [3],
       [2],
       [3],
       [4],
       [3],
       [2],
       [4],
       [4]])

In [103]:
arr.reshape(4,-1)   # if no of columns are not known

array([[1, 4, 4],
       [1, 3, 2],
       [3, 4, 3],
       [2, 4, 4]])

In [104]:
arr.reshape(4, -100)

array([[1, 4, 4],
       [1, 3, 2],
       [3, 4, 3],
       [2, 4, 4]])

In [105]:
arr.reshape(-2,4)

array([[1, 4, 4, 1],
       [3, 2, 3, 4],
       [3, 2, 4, 4]])

In [106]:
arr.reshape(-2,4).base    # gives the array from which the reshaping is done

array([[1, 4, 4, 1],
       [3, 2, 3, 4],
       [3, 2, 4, 4]])

In [107]:
arr            # reshape creates a shallow copy

array([[1, 4, 4, 1],
       [3, 2, 3, 4],
       [3, 2, 4, 4]])

In [108]:
arr.shape

(3, 4)

In [109]:
# changing the dimensions of an array
arr.reshape(2,2,3)    # multiplication rule is always followed   ie (2*2*3) = (3*4)

array([[[1, 4, 4],
        [1, 3, 2]],

       [[3, 4, 3],
        [2, 4, 4]]])

In [110]:
arr.reshape(4,3,1)      # 3 dimensional array

array([[[1],
        [4],
        [4]],

       [[1],
        [3],
        [2]],

       [[3],
        [4],
        [3]],

       [[2],
        [4],
        [4]]])

In [111]:
arr.reshape(1,2,2,3)   # 4 dimensional array

array([[[[1, 4, 4],
         [1, 3, 2]],

        [[3, 4, 3],
         [2, 4, 4]]]])

In [112]:
arr.reshape(4,3,1)

array([[[1],
        [4],
        [4]],

       [[1],
        [3],
        [2]],

       [[3],
        [4],
        [3]],

       [[2],
        [4],
        [4]]])

In [113]:
arr.reshape(1,1,1,1,1,1,1,1,2,2,3)

array([[[[[[[[[[[1, 4, 4],
                [1, 3, 2]],

               [[3, 4, 3],
                [2, 4, 4]]]]]]]]]]])

In [114]:
lis = [1,2,3,4]
arr = np.array(lis)

In [115]:
arr.ndim

1

In [116]:
arr2 = np.array([[2,3],[4,5]])
arr2.ndim

2

In [117]:
arr2 = np.zeros((3,4))
arr2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [118]:
arr3 = np.zeros((1,3,4))  # 3 rows ,4 columns >> 2d array + 1d
arr3

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [119]:
arr3.ndim

3

In [120]:
arr3.shape

(1, 3, 4)

In [121]:
arr3 = np.zeros((1,3,4,1))  # 3 rows ,4 columns >> 2d array + 1d +1d
arr3

array([[[[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]]]])

In [122]:
arr3.ndim

4

In [123]:
arr3.shape


(1, 3, 4, 1)

In [124]:
arr3 = np.zeros((1,3,4))
arr3

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [125]:
arr3 = np.zeros((2,3,4))
arr3

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [126]:
arr3 = np.zeros((3,3,4))
arr3

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [127]:
arr3.ndim

3

In [128]:
arr3.shape

(3, 3, 4)

In [129]:
arr1 = np.random.randint(1,10,(5,6))
arr1

array([[1, 1, 9, 3, 6, 6],
       [7, 3, 5, 7, 1, 8],
       [5, 8, 5, 8, 3, 8],
       [5, 5, 1, 8, 4, 5],
       [1, 3, 9, 6, 9, 3]])

In [130]:
arr1 > 5

array([[False, False,  True, False,  True,  True],
       [ True, False, False,  True, False,  True],
       [False,  True, False,  True, False,  True],
       [False, False, False,  True, False, False],
       [False, False,  True,  True,  True, False]])

In [131]:
arr1[arr1>5]    # to obtain all values where condition is true

array([9, 6, 6, 7, 7, 8, 8, 8, 8, 8, 9, 6, 9])

In [132]:
arr1[arr1<5]

array([1, 1, 3, 3, 1, 3, 1, 4, 1, 3, 3])

In [133]:
arr

array([1, 2, 3, 4])

In [134]:
arr[0]

1

In [135]:
arr[2]

3

In [136]:
arr1

array([[1, 1, 9, 3, 6, 6],
       [7, 3, 5, 7, 1, 8],
       [5, 8, 5, 8, 3, 8],
       [5, 5, 1, 8, 4, 5],
       [1, 3, 9, 6, 9, 3]])

In [137]:
arr1[0]

array([1, 1, 9, 3, 6, 6])

In [138]:
arr1[0][1]

1

In [139]:
arr1[0][1:3]

array([1, 9])

In [140]:
arr1[0,[1,3]]

array([1, 3])

In [141]:
arr1[2:4]

array([[5, 8, 5, 8, 3, 8],
       [5, 5, 1, 8, 4, 5]])

In [142]:
arr1[2:4,[0,2]]

array([[5, 5],
       [5, 1]])

In [143]:
arr1[2:4,0:4]

array([[5, 8, 5, 8],
       [5, 5, 1, 8]])

In [144]:
arr1[[0,4],2:4]

array([[9, 3],
       [9, 6]])

In [145]:
arr1

array([[1, 1, 9, 3, 6, 6],
       [7, 3, 5, 7, 1, 8],
       [5, 8, 5, 8, 3, 8],
       [5, 5, 1, 8, 4, 5],
       [1, 3, 9, 6, 9, 3]])

In [152]:
arr1[[0,4],[2,3]]

array([9, 6])

In [155]:
arr1[[0,1,2,3,4],[0,1,2,3,4]]

array([1, 3, 5, 8, 9])

In [157]:
arr1 = np.random.randint(1,3,(3,3))
arr2 = np.random.randint(1,3,(3,3))

In [158]:
arr1

array([[2, 1, 1],
       [2, 2, 2],
       [2, 1, 2]])

In [159]:
arr2

array([[2, 2, 2],
       [1, 1, 2],
       [2, 1, 2]])

In [163]:
# index wise operations
arr1+arr2

array([[4, 3, 3],
       [3, 3, 4],
       [4, 2, 4]])

In [164]:
arr1-arr2

array([[ 0, -1, -1],
       [ 1,  1,  0],
       [ 0,  0,  0]])

In [165]:
arr1*arr2

array([[4, 2, 2],
       [2, 2, 4],
       [4, 1, 4]])

In [170]:
# matrix multiplication but multiplication must be defined ie no of columns must be equal to the no of rows in the second matrix
arr1

array([[2, 1, 1],
       [2, 2, 2],
       [2, 1, 2]])

In [171]:
arr2

array([[2, 2, 2],
       [1, 1, 2],
       [2, 1, 2]])

In [169]:
arr1 @ arr2    # also called as the dot product

array([[ 7,  6,  8],
       [10,  8, 12],
       [ 9,  7, 10]])

In [172]:
arr1 / arr2   # index wise division

array([[1. , 0.5, 0.5],
       [2. , 2. , 1. ],
       [1. , 1. , 1. ]])

In [174]:
arr1 / 0      # numpy understands infinity

C:\Users\haris nazir\AppData\Local\Temp\ipykernel_12048\2989733664.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1 / 0      # numpy understands infinity


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [175]:
# broad casting doing things to all of the elements of an array

In [177]:
arr = np.zeros((3,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [178]:
arr + 5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [180]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [181]:
arr + a

ValueError: operands could not be broadcast together with shapes (3,4) (5,) 

In [182]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [183]:
arr + a         # column wise addition

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [184]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [185]:
arr + a

ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

In [186]:
# to add row wise we transpose

In [194]:
a = np.array([[1,2,3]])
a.T

array([[1],
       [2],
       [3]])

In [195]:
arr + a

ValueError: operands could not be broadcast together with shapes (3,4) (1,3) 

In [196]:
arr + a.T

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.]])

In [197]:
a = np.array([1,2,3,4])
a.T

array([1, 2, 3, 4])

In [198]:
a = np.array([[1,2,3,4]])
a.T

array([[1],
       [2],
       [3],
       [4]])

In [199]:
np.sqrt(arr1)

array([[1.41421356, 1.        , 1.        ],
       [1.41421356, 1.41421356, 1.41421356],
       [1.41421356, 1.        , 1.41421356]])

In [200]:
np.log10(arr1)

array([[0.30103, 0.     , 0.     ],
       [0.30103, 0.30103, 0.30103],
       [0.30103, 0.     , 0.30103]])

In [201]:
np.exp(arr1)

array([[7.3890561 , 2.71828183, 2.71828183],
       [7.3890561 , 7.3890561 , 7.3890561 ],
       [7.3890561 , 2.71828183, 7.3890561 ]])

In [202]:
np.min(arr1)

1

In [203]:
np.min(a)

1

In [204]:
np.max(arr1)

2

In [205]:
# dimensions
# reduce dimension
arr1.flatten()

array([2, 1, 1, 2, 2, 2, 2, 1, 2])

In [207]:
# expand dimensions >> expand the array by inserting a new axis
# axis = 1 column wise   adds rows
# axis = 0 row wise     adds columns
arr = np.array([[1,2,3],[6,7,8]])
arr

array([[1, 2, 3],
       [6, 7, 8]])

In [209]:
np.sum(arr)

27

In [210]:
arr = np.array([[1,2,3],[6,7,8],[7,3,1]])
arr

array([[1, 2, 3],
       [6, 7, 8],
       [7, 3, 1]])

In [214]:
np.sum(arr,axis = 0)   # row wise addition

array([14, 12, 12])

In [215]:
np.sum(arr,axis = 1)

array([ 6, 21, 11])

In [218]:
# expand dimensions
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [217]:
arr.ndim

1

In [219]:
arr1 = np.expand_dims(arr,axis = 0)
arr1

array([[1, 2, 3, 4]])

In [220]:
arr2 = np.expand_dims(arr1,axis = 0)
arr2

array([[[1, 2, 3, 4]]])

In [221]:
arr2.shape

(1, 1, 4)

In [222]:
arr1 = np.expand_dims(arr,axis = 1)
arr1

array([[1],
       [2],
       [3],
       [4]])

In [223]:
arr1.shape

(4, 1)

In [224]:
arr1 = np.expand_dims(arr,axis = 1)
arr1

array([[1],
       [2],
       [3],
       [4]])

In [225]:
arr1.shape

(4, 1)

In [252]:
arr = np.zeros((3,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [253]:
arr1 = np.expand_dims(arr,axis = 1)
arr1

array([[[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]]])

In [246]:
arr.shape

(1, 3, 4)

In [254]:
arr1 = np.expand_dims(arr,axis = 0)
arr1

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])